-- Check if the current buffer's file type is "ipynb"
--local function set_tab_size()
--    local bufname = vim.fn.expand('%:p:h')
--    if string.find(bufname, 'MyISA') then 
--        vim.opt.tabstop = 2
--        vim.opt.softtabstop = 2
--        vim.opt.shiftwidth = 2
--    else
--        vim.opt.tabstop = 4
--        vim.opt.softtabstop = 4
--        vim.opt.shiftwidth = 4
--    end
--end

--vim.cmd('autocmd BufEnter * lua set_tab_size()')
--vim.cmd('autocmd BufRead * lua set_tab_size()')
-- local function is_ipynb()
--     return vim.fn.expand("%:e") == "ipynb"
-- end
--
-- -- Configurations for vim-jupyter plugin
-- if is_ipynb() then
--     -- Add the configuration for vim-jupyter here
--     -- For example:
--     vim.cmd("let g:jupyter_enable_mappings = 1")
--     vim.cmd("let g:jupyter_start_on_init = 0")
--     -- Add other configurations as needed
-- end
--
