-- local obsidian = require("obsidian")
-- local plenary = require("plenary")
--
-- obsidian.setup({
--   workspaces = {
--     {
--       name = "Diary",
--       path = "/Users/micael/Google Drive/My Drive/Obsidian/Diary",
--     },
--     {
--       name = "MintT",
--       path = "/Users/micael/Google Drive/My Drive/Obsidian/MintT",
--     },
--   },
-- })
